server:
  port: 8080

spring:
  application:
    name: idempotency-demo
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

logging:
  level:
    root: WARN
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR

datasource:
  url: jdbc:h2:mem:idempotency_demo
  driver-class-name: org.h2.Driver
  username: sa
  password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  kafka:
    bootstrap-servers: broker:29092
    consumer:
      group-id: idempotency-demo
      auto-offset-reset: earliest
      enable-auto-commit: true # transport decoupled
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: RECORD
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
topics:
  input: hello-world
  dlq:
    pipeline: hello-world.dlq
    business: hello-world-business.dlq
